name: Trigger auto deployment for scroot-c8718726

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/scroot-c8718726-AutoDeployTrigger-b71b4509-d227-4fb1-845c-1497b915b157.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SCROOTC8718726_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SCROOTC8718726_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SCROOTC8718726_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: cappsinttestregistryprivate.azurecr.io
          registryUsername: ${{ secrets.SCROOTC8718726_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SCROOTC8718726_REGISTRY_PASSWORD }}
          containerAppName: scroot-c8718726
          resourceGroup: cappsint-eastasia-cni
          imageToBuild: cappsinttestregistryprivate.azurecr.io/scroot-c8718726:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


