name: Trigger auto deployment for scroot-7ca4b2bc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/scroot-7ca4b2bc-AutoDeployTrigger-faa3a663-9220-4e0c-8d4f-78c926f2fe94.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SCROOT7CA4B2BC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SCROOT7CA4B2BC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SCROOT7CA4B2BC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: cappsinttestregistryprivate.azurecr.io
          registryUsername: ${{ secrets.SCROOT7CA4B2BC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SCROOT7CA4B2BC_REGISTRY_PASSWORD }}
          containerAppName: scroot-7ca4b2bc
          resourceGroup: cappsint-rg
          imageToBuild: cappsinttestregistryprivate.azurecr.io/scroot-7ca4b2bc:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


