name: Trigger auto deployment for scroot-b79d73d2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/scroot-b79d73d2-AutoDeployTrigger-73160e85-a182-4902-85e0-3c0da75d1a4f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SCROOTB79D73D2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SCROOTB79D73D2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SCROOTB79D73D2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: cappsinttestregistryprivate.azurecr.io
          registryUsername: ${{ secrets.SCROOTB79D73D2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SCROOTB79D73D2_REGISTRY_PASSWORD }}
          containerAppName: scroot-b79d73d2
          resourceGroup: cappsint-westus2-cni
          imageToBuild: cappsinttestregistryprivate.azurecr.io/scroot-b79d73d2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


