name: Trigger auto deployment for scroot-48ee2825

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/scroot-48ee2825-AutoDeployTrigger-3f4551d2-8644-45d2-97d3-b60669650e8a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SCROOT48EE2825_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SCROOT48EE2825_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SCROOT48EE2825_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: cappsinttestregistryprivate.azurecr.io
          registryUsername: ${{ secrets.SCROOT48EE2825_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SCROOT48EE2825_REGISTRY_PASSWORD }}
          containerAppName: scroot-48ee2825
          resourceGroup: cappsint-eu2euap-cni-dedicated-nonvnet
          imageToBuild: cappsinttestregistryprivate.azurecr.io/scroot-48ee2825:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


